name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
        
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
        
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'
        
      - name: Build with Maven
        run: mvn clean install
